=== jonatron55/namegen/configs/namegen.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
  <!--
    Rust's bool parser accepts only "true" and "false"; xs:boolean would also
    admit "0" and "1".
  -->
  <xs:simpleType name="Boolean">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true" />
      <xs:enumeration value="false" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Probability">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CapitalizerMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AllLower" />
      <xs:enumeration value="FirstUpper" />
      <xs:enumeration value="AllUpper" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NumberStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dec" />
      <xs:enumeration value="Decimal" />
      <xs:enumeration value="Hex" />
      <xs:enumeration value="HexUpper" />
      <xs:enumeration value="HexadecimalUpper" />
      <xs:enumeration value="HexLower" />
      <xs:enumeration value="HexadecimalLower" />
      <xs:enumeration value="Oct" />
      <xs:enumeration value="Octal" />
      <xs:enumeration value="Bin" />
      <xs:enumeration value="Binary" />
      <xs:enumeration value="Roman" />
      <xs:enumeration value="RomanUpper" />
      <xs:enumeration value="RomanLower" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="NameGen">
    <xs:annotation>
      <xs:documentation>
        Root element of a name generator configuration. Contains an optional
        &lt;Description&gt; followed by exactly one generator or combiner.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Description" type="Description" minOccurs="0" />
        <xs:group ref="Part" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Description" mixed="true">
    <xs:annotation>
      <xs:documentation>
        Human-readable metadata. The element's text content is the description
        shown to the user; &lt;Param&gt; children name the constrainable ids.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            Display name for a constrainable element id. Each id may appear at
            most once.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="display_name" type="xs:string" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="display_name" type="xs:string" default="Unnamed Generator" />
  </xs:complexType>

  <!-- ==================== Generators and combiners ==================== -->

  <xs:group name="Part">
    <xs:annotation>
      <xs:documentation>Any generator or combiner element.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="Capitalize" type="Capitalize" />
      <xs:element name="Join" type="Join" />
      <xs:element name="Literal" type="Literal" />
      <xs:element name="Markov" type="Markov" />
      <xs:element name="Match" type="Match" />
      <xs:element name="Number" type="Number" />
      <xs:element name="Option" type="Option" />
      <xs:element name="Repeat" type="Repeat" />
      <xs:element name="Switch" type="Switch" />
      <xs:element name="Words" type="Words" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="Capitalize">
    <xs:annotation>
      <xs:documentation>
        Changes the capitalization of the output of its single child.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="mode" type="CapitalizerMode" default="FirstUpper" />
  </xs:complexType>

  <xs:complexType name="Join">
    <xs:annotation>
      <xs:documentation>
        Concatenates the output of its children, separated by "sep". A
        &lt;Reject&gt; child lists whitespace-separated results to reroll.
      </xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="Part" />
      <xs:element name="Reject" type="xs:string" />
    </xs:choice>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="sep" type="xs:string" default="" />
  </xs:complexType>

  <xs:complexType name="Literal">
    <xs:annotation>
      <xs:documentation>
        Inserts a fixed string into the output. Must be empty.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="text" type="xs:string" default="" />
  </xs:complexType>

  <!--
    Not expressible here: at most one tokenizer child is allowed. The parser
    rejects a second one.
  -->
  <xs:complexType name="Markov" mixed="true">
    <xs:annotation>
      <xs:documentation>
        Generates words from a Markov chain. The element's text content is the
        whitespace-separated training data.
      </xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Reject" type="xs:string" />
      <xs:element name="SplitTokenizer" type="SplitTokenizer" />
      <xs:element name="ChunkTokenizer" type="ChunkTokenizer" />
      <xs:element name="SspTokenizer" type="SspTokenizer" />
    </xs:choice>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="target_min" type="xs:nonNegativeInteger" />
    <xs:attribute name="target_max" type="xs:nonNegativeInteger" />
    <xs:attribute name="uniform" type="Boolean" default="false" />
    <xs:attribute name="reject_training" type="Boolean" default="false" />
  </xs:complexType>

  <xs:complexType name="Match">
    <xs:annotation>
      <xs:documentation>
        Runs its first child, then runs the &lt;Case&gt; whose regex matches
        that output, or &lt;Default&gt; if none match. Cannot be constrained.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
      <xs:element name="Case" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="Part" />
          </xs:sequence>
          <!-- Regex syntax is that of the Rust regex crate; not checked here. -->
          <xs:attribute name="expr" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
      <xs:element name="Default" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="Part" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <!-- Not expressible here: min must be less than or equal to max. -->
  <xs:complexType name="Number">
    <xs:annotation>
      <xs:documentation>
        Emits a random number in [min, max]. Must be empty.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="min" type="xs:nonNegativeInteger" default="1" />
    <xs:attribute name="max" type="xs:nonNegativeInteger" default="99" />
    <xs:attribute name="style" type="NumberStyle" default="Decimal" />
  </xs:complexType>

  <xs:complexType name="Option">
    <xs:annotation>
      <xs:documentation>
        Runs its single child with the given probability.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="probability" type="Probability" default="0.5" />
  </xs:complexType>

  <!-- Not expressible here: min must be less than or equal to max. -->
  <xs:complexType name="Repeat">
    <xs:annotation>
      <xs:documentation>
        Runs its single child between min and max times.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="min" type="xs:nonNegativeInteger" default="1" />
    <xs:attribute name="max" type="xs:nonNegativeInteger" default="2" />
  </xs:complexType>

  <xs:complexType name="Switch">
    <xs:annotation>
      <xs:documentation>
        Runs exactly one randomly selected child.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="Words">
    <xs:annotation>
      <xs:documentation>
        Selects one word at random from its whitespace-separated text content.
      </xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="SplitTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words on the given characters. Defaults to "/".
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="split_chars" type="xs:string" default="/" />
  </xs:complexType>

  <xs:complexType name="ChunkTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words into fixed-length chunks of "len" characters.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="len" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="SspTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words into syllables using the sonority sequencing
        principle. With no &lt;Class&gt; children, a default ranking is used.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Class" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            Assigns a sonority rank to each character in the text content;
            higher is more sonorous.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="rank" type="xs:unsignedByte" use="required" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== jonatron55/namegen/configs/epick.xml
<?xml version="1.0" encoding="UTF-8"?>
<NameGen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="namegen.xsd">
  <Description display_name="Epick Phantasie">
    <Param id="firstname" display_name="First name" />
    <Param id="surname" display_name="Surname" />
    Produces the most epick of phantasie names taken from forbidden grimoires of
    dark and ancient magicks. These grand names are fit only for the edgiest of
    edgelordes.
  </Description>
  <Join sep=" ">
    <Switch>
      <Markov id="firstname" target_min="4" target_max="10">
        Abaddon Abraxas Acheron Achilles Ada Adeline Aeneas Aerial Agamemnon Aiden Ajax
        Alaric Alexander Alfred Alioth Amber Ambrosius Andromeda Angus Antares Anubis
        Aphrodite Apollo Aquarius Areal Ares Ariadne Artemis Arthur Asclepius Ash
        Asmodeus Asreal Astaroth Astrid Athena Atlas Atticus Auberon Augusta Augustus
        Aurelius Azrael Bacchus Baldr Baldur Bane Baphomet Bastet Beelzebub Behemoth
        Belial Belinda Bellatrix Bellerophon Belphegor Beowulf Berrant Bjarne Bjorn
        Blaphomet Blaze Bramble Brand Brandon Brimstone Cadfeal Cadmus Caius Caligula
        Calliope Calypso Cambiel Castor Cato Celestia Cerberus Cernunnos Chaos Charon
        Chastity Chiron Chronos Circe Claudius Cleopatra Colossus Condor Conor Corvus
        Craze Cronus Cupid Cygnus Cyrus Daedalus Dagon Damion Damocles Dariel Darius
        Delilah Demeter Desdemona Despina Diabolus Diana Dionysus Django Dominique
        Dorian Draco Draconis Dracula Draven Drusilla Drusus Dylan Dædalus Eden Eir
        Elizabeth Elysium Endymion Erebus Eris Eros Eternity Eurydice Evangeline Eve
        Faust Faustus Fenrir Fionn Freya Gabriel Gaia Galadriel Galahad Galatea Gale
        Ganymede Gawain Genghis Gideon Gilgamesh Gloria Goliath Gorgon Grendel Guinevere
        Hades Hannibal Hazel Hecate Hector Hel Hela Helena Helga Helios Helix Hephaestus
        Hera Heracles Hercules Hermes Hestia Hexxus Hilda Hildegarde Horus Hrothgar
        Hypatia Hyperion Hypnos Icarus Ignatius Imogen Imperia Imperius Io Isis Isolde
        Jack Janus Jareth Jasmine Jason Jericho Jester Judas Julius Juno Jupiter Kael
        Kali Kassandra Khan Kronos Lance Lancelot Lazarus Leander Leonidas Leonora
        Leviathan Lilith Loki Lorelei Lucifer Lucius Luna Lysander Macleod Magellan
        Magnus Magus Mammon Mars Matilda Maverick Maxima Maximus Medusa Melchior
        Mercedes Mercury Mercy Merlin Mesmer Minerva Mordred Morgan Morgana Morgause
        Morpheus Morphine Morrigan Mortimer Murmur Mystery Narcissus Nemesis Nephthys
        Neptune Nereus Nike Nimue Nyx Oberon Octavia Odin Odysseus Oedipus Ophelia Orion
        Orpheus Osiris Pan Pandora Paradoxia Paradoxius Paris Patroclus Pegasus
        Penndragon Persephone Perseus Phoebe Phoenix Pluto Poseidon Prometheus Prospero
        Psyche Puck Quasimodo Quintus Ragnar Raijin Raziel Rhea Rhiannon Rhiva Romulus
        Sable Sabriel Samael Samson Samuel Saphiel Sapphira Saturn Seeker Selene Seraph
        Seraphina Shiva Sigurd Sirius Skadi Sobek Solitaire Solomon Solstice Stiletto
        Tarot Temperance Thaddaeus Thalassa Thalassia Thanatos Themis Theophantos
        Theseus Thor Thoth Tiamat Titania Tobias Triton Tyr Ulysses Uranus Uriel Ursa
        Ursula Valentina Valentine Valour Venus Vercingetorix Vesper Vespera Vesta
        Vesuvius Vex Veyra Veyron Veyronia Veyronius Veyronyxia Victor Victoria Vladimir
        Vorion Vulcan Wallace Washington Watson Wolfgang Wormwood Xanthe Xavier Xena
        Xeno Xerxes Xylander Yggdrasil Ymir Ysolde Yvaine Zacharias Zachariel Zagreus
        Zephron Zephyr Zephyrine Zephyrus Zethus Zeus Zoltan Zora Zorina Zorion Zorya
        Zyra Zythia
      </Markov>
    </Switch>
    <Switch>
      <Words id="surname">
        Abjuror Abyssal Aeromancer Albion Alchemist Angel Apostate Arcana Arcane Arcanum
        Archangel Archon Artificer Assassin Augur Avatar Baleful Basilisk Berserker
        Blizzard Bloodoracle Cacodæmon Celestial Chimera Chronomancer Claymore Conjuror
        Crimson Cryomancer Crystal Cyclops Damned Destroyer Divine Diviner Draco Dracula
        Drake Dreadnought Dreamweaver Dæmon Dæmonifuge Dæmonslayer Eagle-eye Eclipse
        Eldritch Electromancer Ember Enchanter Enchantress Enigma Enigmatic Enraptured
        Enslaver Ensorcelled Enticer Entwined Eternal Evermore Exorcist Falconer
        Fireball Forsaken Færie Geomancer Gladiator Godslayer Gorgon Grimoire
        Hammersmite Harpy Hawkeye Heretic Hexblade Hydromancer Illusionist Incubus
        Infernal Jackal Jaeger Juggernaut Kraken Legend Leviathan Lightning Lycanthrope
        Magus Maledictor Mancubus Manticore Marauder Metatron Midnight Minotaur Mystic
        Necromancer Nightengale Nightmare Oblivion Omen Oracle Orcus Paladin
        Pandæmonium Paracosm Paradox Phantasie Phantasm Phantom Phobia Photon Prism
        Profane Psion Pyromancer Quake Ragnarok Rainbow Ravager Reaper Revenant
        Sabertooth Scarlet Scion Seer Seeress Seraphim Shadow Smiter Soothsayer Sorcerer
        Sorceress Spectre Squander Strider Succubus Summoner Thaumaturge Twilight
        Typhoon Undertaker Vampire Venom Venomsoul Vulture Warlock Warlord Wendigo
        Werewolf Wizard Wraith Zephyr
      </Words>
      <Join>
        <Words id="surname">
          Arch Ashen Astral Battle Beast Black Blood Blue Bone Brave Bronze Brown Crimson
          Crystal Dark Dawn Death Deep Doom Dragon Dread Dream Dusk Dæmon Earth Elden
          Ember Ever Fate Fey Fiend Fire Ghost Ghoul Giant Gloom God Gorgon Grave Great
          Grief Grim Gryphon Hammer Hate Hawk Hell Hero Hex High Iron Kill Kraken Lion
          Lizard Lych Mad Mammoth Mist Monster Mourn Night Oaken Phantom Poison Raven Rune
          Serpent Shadow Sin Skull Sorrow Soul Spell Star Steel Storm Sun Thunder Titan
          Troll Under Venom Void Wander War Wight Wild Wind Winter Witch Wolf Wraith Wyrm
          Wyvern Ælder
        </Words>
        <Words>
          axe blade blessed blood born breaker bringer caller caster chant cinder claw
          cloak cloud conjure cursed dagger dark doom dread dreamer eater eye fallen fang
          fate fire flayer folk forged frozen ghost grim guard hand heart helm hexxor holy
          hunt hunter keeper killer kin kind king knight light lord lost magick master
          meister might mind mourner murder night phantom priest python queen raven reaper
          rider rogue sabre sbane scythe seeker shadow shaker singer sinner skull sky
          slayer smite song sorrow soul speaker spectre spell spire stalker stealer stomp
          storm strider summoner sure sword talon thief thorn true walker ward weaver wing
          winter wise witch wolf wraith wrath wyrm
        </Words>
      </Join>
    </Switch>
  </Join>
</NameGen>
