=== jonatron55/namegen/configs/namegen.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
  <!--
    Rust's bool parser accepts only "true" and "false"; xs:boolean would also
    admit "0" and "1".
  -->
  <xs:simpleType name="Boolean">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true" />
      <xs:enumeration value="false" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Probability">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CapitalizerMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AllLower" />
      <xs:enumeration value="FirstUpper" />
      <xs:enumeration value="AllUpper" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NumberStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dec" />
      <xs:enumeration value="Decimal" />
      <xs:enumeration value="Hex" />
      <xs:enumeration value="HexUpper" />
      <xs:enumeration value="HexadecimalUpper" />
      <xs:enumeration value="HexLower" />
      <xs:enumeration value="HexadecimalLower" />
      <xs:enumeration value="Oct" />
      <xs:enumeration value="Octal" />
      <xs:enumeration value="Bin" />
      <xs:enumeration value="Binary" />
      <xs:enumeration value="Roman" />
      <xs:enumeration value="RomanUpper" />
      <xs:enumeration value="RomanLower" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="NameGen">
    <xs:annotation>
      <xs:documentation>
        Root element of a name generator configuration. Contains an optional
        &lt;Description&gt; followed by exactly one generator or combiner.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Description" type="Description" minOccurs="0" />
        <xs:group ref="Part" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Description" mixed="true">
    <xs:annotation>
      <xs:documentation>
        Human-readable metadata. The element's text content is the description
        shown to the user; &lt;Param&gt; children name the constrainable ids.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            Display name for a constrainable element id. Each id may appear at
            most once.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="display_name" type="xs:string" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="display_name" type="xs:string" default="Unnamed Generator" />
  </xs:complexType>

  <!-- ==================== Generators and combiners ==================== -->

  <xs:group name="Part">
    <xs:annotation>
      <xs:documentation>Any generator or combiner element.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="Capitalize" type="Capitalize" />
      <xs:element name="Join" type="Join" />
      <xs:element name="Literal" type="Literal" />
      <xs:element name="Markov" type="Markov" />
      <xs:element name="Match" type="Match" />
      <xs:element name="Number" type="Number" />
      <xs:element name="Option" type="Option" />
      <xs:element name="Repeat" type="Repeat" />
      <xs:element name="Switch" type="Switch" />
      <xs:element name="Words" type="Words" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="Capitalize">
    <xs:annotation>
      <xs:documentation>
        Changes the capitalization of the output of its single child.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="mode" type="CapitalizerMode" default="FirstUpper" />
  </xs:complexType>

  <xs:complexType name="Join">
    <xs:annotation>
      <xs:documentation>
        Concatenates the output of its children, separated by "sep". A
        &lt;Reject&gt; child lists whitespace-separated results to reroll.
      </xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="Part" />
      <xs:element name="Reject" type="xs:string" />
    </xs:choice>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="sep" type="xs:string" default="" />
  </xs:complexType>

  <xs:complexType name="Literal">
    <xs:annotation>
      <xs:documentation>
        Inserts a fixed string into the output. Must be empty.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="text" type="xs:string" default="" />
  </xs:complexType>

  <!--
    Not expressible here: at most one tokenizer child is allowed. The parser
    rejects a second one.
  -->
  <xs:complexType name="Markov" mixed="true">
    <xs:annotation>
      <xs:documentation>
        Generates words from a Markov chain. The element's text content is the
        whitespace-separated training data.
      </xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Reject" type="xs:string" />
      <xs:element name="SplitTokenizer" type="SplitTokenizer" />
      <xs:element name="ChunkTokenizer" type="ChunkTokenizer" />
      <xs:element name="SspTokenizer" type="SspTokenizer" />
    </xs:choice>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="target_min" type="xs:nonNegativeInteger" />
    <xs:attribute name="target_max" type="xs:nonNegativeInteger" />
    <xs:attribute name="uniform" type="Boolean" default="false" />
    <xs:attribute name="reject_training" type="Boolean" default="false" />
  </xs:complexType>

  <xs:complexType name="Match">
    <xs:annotation>
      <xs:documentation>
        Runs its first child, then runs the &lt;Case&gt; whose regex matches
        that output, or &lt;Default&gt; if none match. Cannot be constrained.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
      <xs:element name="Case" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="Part" />
          </xs:sequence>
          <!-- Regex syntax is that of the Rust regex crate; not checked here. -->
          <xs:attribute name="expr" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
      <xs:element name="Default" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="Part" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <!-- Not expressible here: min must be less than or equal to max. -->
  <xs:complexType name="Number">
    <xs:annotation>
      <xs:documentation>
        Emits a random number in [min, max]. Must be empty.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="min" type="xs:nonNegativeInteger" default="1" />
    <xs:attribute name="max" type="xs:nonNegativeInteger" default="99" />
    <xs:attribute name="style" type="NumberStyle" default="Decimal" />
  </xs:complexType>

  <xs:complexType name="Option">
    <xs:annotation>
      <xs:documentation>
        Runs its single child with the given probability.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="probability" type="Probability" default="0.5" />
  </xs:complexType>

  <!-- Not expressible here: min must be less than or equal to max. -->
  <xs:complexType name="Repeat">
    <xs:annotation>
      <xs:documentation>
        Runs its single child between min and max times.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="min" type="xs:nonNegativeInteger" default="1" />
    <xs:attribute name="max" type="xs:nonNegativeInteger" default="2" />
  </xs:complexType>

  <xs:complexType name="Switch">
    <xs:annotation>
      <xs:documentation>
        Runs exactly one randomly selected child.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="Part" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="Words">
    <xs:annotation>
      <xs:documentation>
        Selects one word at random from its whitespace-separated text content.
      </xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="SplitTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words on the given characters. Defaults to "/".
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="split_chars" type="xs:string" default="/" />
  </xs:complexType>

  <xs:complexType name="ChunkTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words into fixed-length chunks of "len" characters.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="len" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="SspTokenizer">
    <xs:annotation>
      <xs:documentation>
        Splits training words into syllables using the sonority sequencing
        principle. With no &lt;Class&gt; children, a default ranking is used.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Class" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>
            Assigns a sonority rank to each character in the text content;
            higher is more sonorous.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="rank" type="xs:unsignedByte" use="required" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== jonatron55/namegen/configs/goblin.xml
<?xml version="1.0" encoding="UTF-8"?>
<NameGen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="namegen.xsd">
  <Description display_name="Goblinoid Names">
    <Param id="firstname" display_name="First name" />
    <Param id="surname" display_name="Surname" />
    Creates names for goblins, gremlins, and bugaboos.
  </Description>
  <Join sep=" ">
    <Markov id="firstname" target_max="11">
      Aggro Arg Argleblargle Argwog Arklesnarck Arzlewig Barklesnurg Blarkblark Blurm
      Bnarzleback Bnitzlebong Bnurklesnang Bogsnoggle Booglin Braggle Brizzle Buckyuck
      Bugbug Buggle Buggleyuck Buglin Burglebung Buzzlebong Buzzlegunk Choggle Chuggle
      Chuggo Chugwog Chugwoggle Chugwug Chugwuzzle Dargle Dargleblargle Dnitzlediz
      Dogirm Dunzledim Eck Eckblozzo Eckblurgle Ecksnitz Eggle Erckorg Erckozzle
      Ezzlebug Fargle Fnarkle Fnarz Fnazzle Fnig Fniggleblurk Fnitz Fnog Fnurglebonk
      Fnurz Foggo Foglin Fonk Fonkle Fugglesnort Glark Gloggo Glugglesnog Glurg Glurk
      Gluzzleblark Gnargle Gnarkle Gnurklesnargle Gonko Gorgle Gorgo Grackle Grark
      Grazzlesnub Gricklesnip Gritzlebing Grizzle Grizzleblargle Grizzleblark
      Grizzleblurgle Groggo Grozzo Gruggle Grurg Grurk Gruzwuzzle Gruzzle Gullybung
      Gullywog Hargle Hargleblargle Hargleblurgle Harglebluzzle Hoggle Huggle Huggo
      Irklebirkle Irkobbork Itzleblurk Jacko Jaggle Jagwog Jickerblaz Joggler
      Jugglesnog Kergrozzle Kludge Krackleblaz Krucko Kurgo Lerkle Lurkimer Moggle
      Muggler Murkimer Nargle Narglebargle Narkleblaz Nitzsnitz Norkimer Norknork Ogg
      Ogglebog Piggle Pirklesnitz Platzle Plunk Pnitzig Pnucko Pockle Poggo Pollywog
      Porgle Pucksnitz Puggle Puglin Punkle Purkle Quarkle Quogbug Raggle Rargle
      Snaggle Snitzleburk Snogglesnort Snoggum Snoo Snortle Snozzle Snubblub Snuggo
      Snuzangle Snuzle Snuzzle Sockobbock Soggo Splutz Splutzle Struggos Stunk
      Suckobruck Suggle Tangle Targle Tniggle Tnurglurk Troglin Tuggo Turnglebling
      Ubzog Ugg Ugglebiggle Uggo Uggoboggo Uggrug Ugwug Urgle Warckle Warzle Whoggo
      Whuggle Wigglerug Woggle Woggo Wogwog Wozzo Wugglewug Wuglin Wurgle Wuzzlewog
      Yaggle Yockoblock Yogle Yucko Yuggo
    </Markov>
    <Capitalize>
      <Join>
        <Repeat min="2" max="2">
          <Words id="surname">
            anger bad bite biter blade blood bone breaker bug cackle cave claw club crazed
            crooked cruel dark dirt doom dread dumb eater evil eye face fear filth fist foot
            foul glare gloom glum green grey grim grime grin grip grit hand hide horror
            hunter killer knife knuckle lash lasher little mad mean mud murder murmur mutter
            nose pain poison rat rot rotten scream shadow sick skull slicer smack smash
            snake snapper snare snarl snatch snatcher sneak spider stab stare steel stink
            stinker swipe switch tangle teeth terror thief toe tooth trap twist twisted
            weasle worg worm yellow
          </Words>
        </Repeat>
      </Join>
    </Capitalize>
  </Join>
</NameGen>

=== jonatron55/namegen/configs/elf.xml
<?xml version="1.0" encoding="UTF-8"?>
<NameGen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="namegen.xsd">
  <Description display_name="Elven Names">
    <Param id="firstname" display_name="First name" />
    <Param id="gender" display_name="Gender (0: masculine, 1: feminine)" />
    <Param id="surname" display_name="Surname" />
    Generates elven names, inspired by Celtic, Welsh, and various mythological
    sources.
  </Description>
  <Join sep=" ">
    <Switch id="gender">
      <Markov id="firstname" target_min="4" target_max="10">
        Aderiol Adeth Adiol Aerand Aerannol Aerathiand Aeriol Aeron Aerond Ailill
        Amaethon Aneirin Aodh Aonghus Arawn Arthfael Bedivere Belanor Belenos Brandior
        Brochfael Cadfael Cael Carrinnor Cernunnos Connla Conor Coriand Cynwrig Dagda
        Deimne Deinniol Dewydd Diarmaid Dylan Eannin Earand Earin Earond Eilieth Eiliol
        Einion Einiond Eirdor Ellarond Ellethiand Ellonviol Elluthiol Elluvior Eoghan
        Eonthiol Eremon Evand Evandiol Faedior Faennin Faeonel Fearghas Fionn Gareth
        Glenndower Gofannon Goronwy Gwenddoleu Gwydion Halamar Heilyn Herule Heruli
        Ianiol Ianor Iorwerth Iriol Iruthiond Iuand Iuthol Ivaran Jannalor Lamruil Llew
        Llyr Luthais Luthior Luvieth Lythinn Maelgwn Manawydan Mealcun Merfyn Mermin
        Morcant Myarand Myaron Myrddin Naoise Neirin Nuada Nunviond Nuvian Nynniaw
        Oissine Parthalan Peredur Pwyll Rheviand Rhiviond Rhondor Rhosior Segdae Seisyll
        Sharian Shariand Sharinnor Slaine Sudiond Syareth Syorond Taliesin Tanriond
        Taranis Tariond Thaliand Thardiond Tharidinn Toriand Trahern Tryariol Tutgual
        Tyorwer Uthyr Vandiol Voridower Vorior Ywain Zelphar
      </Markov>
      <Markov id="firstname" target_min="4" target_max="10">
        Aderyn Aerafrin Aerathielle Aerona Aeronvia Aeronwen Agrona Aife Ailbhe Andraste
        Angharad Anwen Aoife Ayda Blathine Blodeuedde Branwen Branwenne Bronwyn Carrian
        Ceibfionne Cithrel Cliodna Corianna Daireanne Dairine Derdriu Eadan Eadaoinne
        Eafrin Eawen Eawynne Eilwyn Eirian Eirwen Eithne Ellarwyn Ellethia Ellonvia
        Elluthia Elluvia Eonoa Eonthia Etainne Faewen Faewynne Fayelle Fayonelle
        Feyarwyn Feyelle Feyonoa Finnguala Fionnuala Gladys Glorafrin Gloriel Grainne
        Gwenda Gwendolynne Gwenna Gwennyth Gwynna Gwynnyth Iriel Iruthia Jasianna
        Lorasatra Luthiel Luvioa Lythianna Maeve Matrona Merethyl Merialeth Merrianna
        Morafrin Morgan Morriganne Morwen Morwynne Muirenne Muirne Neamhainne Neasa
        Nithenoel Nolwen Nunvioa Olwenne Paphyra Quennalynne Rheva Rhiannon Rhiva
        Rhonwynne Rhosyn Rigantona Sabia Saphielle Shyannon Shyarwen Sinanne Sionanne
        Sirona Solana Sophia Syarelle Syareth Taegen Tanila Tannaquille Tarieth Tiriana
        Tolwyn Toria Urosynne Ursalynne Ursula Urwyn Violette Voriel Vorionia Yvaine
        Yvonne Zaleria
      </Markov>
    </Switch>
    <Join>
      <Words id="surname">
        Ash Ashen Autumn Bark Birch Bird Blossom Blue Bracken Bramble Brave Breeze
        Bright Brook Bush Cloud Cold Cool Crow Dark Dawn Day Dream Drift Dusk Ember Ever
        Fair Falcon Far Feather Fenn Fern Fey Fire Flame Forest Frost Green Grey Hail
        Hawk High Hunt Leaf Light Merry Mist Moon Nettle Night Oak Oaken Ocean Owl Pale
        Pine Quick Rain Raven River Rose Sapling Seeker Shade Shadow Shore Shrub Silver
        Sky Sparrow Spell Staff Star Storm Summer Sun Swift Thorn Tree Twig Vine Wander
        Whisper Wild Willow Wind Winter Wood Wooden Wren Yew
      </Words>
      <Words>
        bark birch bird bloom blossom bow bracken bramble branch breeze briar brook bush
        caller caster cliff cloud crow dance dancer dawn dreamer drifter dusk dweller
        fair falcon feather fenn fern fey fire flame forest frost gale hail hawk heart
        hunter keen leaf light merry mist moon moss nettle night oak pine rain raven
        river rose sapling sea seed seeker seer shade shadow shore shrub silver singer
        sky song soul sparrow spell staff star stave strider summer sun sure swift thorn
        treader tree twig twiggy twigs vine walker wander wanderer whisper wild willow
        wind wing winter wise wood woods
      </Words>
    </Join>
  </Join>
</NameGen>

=== jonatron55/namegen/configs/dwarf.xml
<?xml version="1.0" encoding="UTF-8"?>
<NameGen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="namegen.xsd">
  <Description display_name="Dwarven Names">
    <Param id="firstname" display_name="First name" />
    <Param id="gender" display_name="Gender (0: masculine, 1: feminine)" />
    <Param id="surname" display_name="Surname" />
    Produces dwarven names, based mainly on Old Norse, Anglo-Saxon, and Germanic
    names, with a few from other sources.
  </Description>
  <Join sep=" ">
    <Switch id="gender">
      <Join>
        <Markov id="firstname" target_min="3" target_max="10">
          <SspTokenizer>
            <Class rank="5">AEIOUYaeiouy</Class>
            <Class rank="4">JWjw</Class>
            <Class rank="3">HLRhlr</Class>
            <Class rank="2">FMNSVZfmnsvzÐÞðþ</Class>
            <Class rank="1">BCDGKPQTXbcdgkpqtx</Class>
          </SspTokenizer>
          Agmundr Agnar Agnarr Agnur Agronn Aleifr Alfarr Alfrikr Alfvin Algautr Andor
          Anundr Anðor Arnfinnr Arnorr Arnsteinn Arnviðr Arnþorr Asbjarn Asbjorn
          Asbrond Asgeirr Asgorn Asgrond Asketill Asmundor Asmundr Asvaldr Authun Auðr
          Auðun Aðalsteinn Bada Baggi Barðr Beogrim Beorhtric Beorhtsige Beornræd
          Beowulf Birgir Bjarn Bjarni Bjartr Bjorn Botwulf Brand Brandr Brock Brond Bronn
          Broðir Brynjarr Burgheard Dag Dagfinn Dagfinnr Dagn Dagr Danr Dudda Dunstan
          Eadwulf Ealdhelm Ealdræd Ealhstan Eardwulf Egill Eidriþ Eileifr Einarr
          Eindriði Eirick Eirikr Erlend Erlendr Erlingr Eysteinn Eyvindr Fastulf Fastulfr
          Felagi Finnr Flaeming Flæmingr Folki Friðþjofr Froði Froþi Gauti Gautstafr
          Geir Geirmundr Geirr Gisli Gjord Gjurd Godric Gulbrandr Gunni Gunnvaldr
          Guðbrandr Guðfroðr Guðini Guðleifr Guðmundr Guðormr Guðroðr Guðþormr
          Hakon Halfdan Hallbjorn Halli Hallr Hallsteinn Hallvarðr Hallþorr Hamundr
          Haraldr Harðaknutr Haukr Havarðr Helgi Hemingr Hereward Herleifr Hildræd
          Hjalmarr Holmgeirr Hoskuldr Hrafn Hreiðarr Hroaldor Hroaldr Hroar Hroarr Hrolfr
          Hrorikr Hroðgar Hroðgeirr Hroðulf Hroðulfr Hroðvaldr Hroðwulf Hroþgar
          Hrœrekr Hugleikr Hæth Ingi Ingimarr Ingolfr Ivarr Joarr Josteinn Kalfr Kari
          Ketill Knutr Kolr Kori Leifr Mundi Njall Odalric Oddbjorn Oddgeirr Oddr Oddvarr
          Olvir Orsic Osgar Ottarr Ragnarr Ragnvaldr Randulfr Raðulfr Runi Sigeberht
          Sigeweard Sigfroðr Sigsteinn Sigurðr Snorri Solvi Somerled Stali Steinarr
          Steingrimr Steinn Stigandr Stigr Stiþwulf Sture Sturla Styrmir Sumarliði
          Sundri Suni Sveinn Sveinungr Sverrir Swiðhun Tofi Toki Tryggvi Ulfr Ulrich Uni
          Urist Vagn Valdimarr Valþjofr Vebjorn Vegarðr Vemundr Vetrliði Vigi Vikingr
          Vragi Widogast Wighard Woden Wulfgang Wulfgeirr Wulfgrim Wulfhard Wulfhram
          Yngvarr Yrian Ælfgar Ælfræd Æsc Æthelberht Æðelbeald Æðelfrið
          Æðelmær Æðelric Æðelræd Æðelstan Æðelwine Æðelwulf Æþelbald
          Æþelbeorht Æþelnoð Æþelræd Æþelweald Æþelweard Æþelwulf Þorarinn
          Þorbjorn Þorfastr Þorfinnr Þorfreðr Þorgeirr Þorgisl Þorgnyr Þorgrimr
          Þorir Þorketill Þorleifr Þorleikr Þormoðr Þorsteinn Þorvaldr Þorðr
          Þrondr Þunor
        </Markov>
        <Option probability="0.25">
          <Literal text="son" />
        </Option>
      </Join>
      <Markov id="firstname" target_min="3" target_max="10">
        <SspTokenizer>
          <Class rank="5">AEIOUYaeiouy</Class>
          <Class rank="4">JWjw</Class>
          <Class rank="3">HLRhlr</Class>
          <Class rank="2">FMNSVZfmnsvzÐÞðþ</Class>
          <Class rank="1">BCDGKPQTXbcdgkpqtx</Class>
        </SspTokenizer>
        Alfhildr Alof Angrboða Arnbjorg Asa Asgerðr Ashildr Aslaug Asny Asta Astriðr
        Auðrhildr Bealdhild Bergljot Birna Bjorg Borghild Borghildr Borgny Bothildr
        Brynhild Brynhildr Cyneburga Cyneswiþ Cyneðryð Dagmær Dagny Dagrun Eadburga
        Eadgyð Ealdgyð Ealhswiþ Eir Elli Embla Eoforhild Eoforhildr Eormenhild Erna
        Eydis Eyvor Frea Freya Freyja Frig Frigg Friða Friðuswiþ Gefion Gefjon Gerd
        Gerðr Godgifu Godgyð Grid Grimhild Grimhildr Griðr Groa Gudrun Gulla
        Gunnbjorg Gunnhildr Gunnr Gunnvor Guðbjorg Guðlaug Guðleif Guðny Guðriðr
        Guðrun Gyða Hallbjorg Hallþora Heidrun Heiðrun Hel Hilda Hildigunnr Hildr
        Hjordis Hlif Holmfriðr Hrafnhildr Hreiðunn Hrǫnn Huld Hulda Idun Idunn
        Ingibjorg Ingigerðr Ingriðr Ingvildr Iðunn Jorunnr Kara Ketillaug Ketilriðr
        Kolbrun Laufey Leofdæg Leofflæd Leofgyð Magnhildr Malmfriðr Milburga
        Mildþryð Myrgjol Nal Nanna Oddbjorg Oddny Oddrun Olaug Ragnbjorg Ragnfriðr
        Ragnheiðr Ragnhildr Ran Runa Saga Salbjorg Saldis Sif Signy Sigriðr Sigrun
        Sigyn Siv Skadi Skaði Skuld Sol Solveig Sunngifu Sunnifa Sunniva Svanhild
        Svanhildr Thrud Tofa Unnr Urd Urðr Valdis Vanadis Verdandi Verðandi Vigdis
        Wihtburg Wilburg Wulfflæd Wulfgifu Wulfrun Wulfwynn Wulfþryð Wynnflæd
        Yngvildr Yrsa Æbbe Ælfthryth Ælfþryð Æðelflæd Æðelþryð Þone Þora
        Þorbjorg Þordis Þorfriðr Þorgunnr Þorhildr Þorny Þorunn Þorveig Þorvi
        Þruðr Þyri
      </Markov>
    </Switch>
    <Join>
      <Words id="surname">
        Ale Aluminium Amber Anvil Ashen Battle Bear Beer Black Blue Bold Brass Brave
        Brick Bronze Brown Cave Cavern Chisel Coal Copper Crimson Dark Deep Diamond Dig
        Dirt Doom Dragon Drunken Earth Ember Emerald Epic Flint Gem Giant Glory Gold
        Golden Gravel Graven Great Green Grendel Grey Grit Grumble Hammer Hard Heavy
        Honour Iron Lead Legend Metal Mountain Noble Oaken Old Pale Pebble Proud Quartz
        Red Rock Rough Ruby Rust Silver Steel Stone Stout Strong Stronginthe Thunder Tin
        Troll Tungsten Under War White Wild Yellow
      </Words>
      <Words>
        arm armour axe bastard beard bellow belly belt blade bold boot born boulder
        buckle chest chin chisel crafter deep delver depth digger diggy doom drinker
        face fall fast feast fighter fire fist flame flint forge forged fort gate glory
        gold grim grip ground grumble guard guts hall hammer heart hearth helm hide
        honour hound humble jewel keg kin labour legend master mighty miner mood
        mountain pebble pick quake quarry quartz rock rocky ruby rust rusty saga shield
        slayer slumber smasher smiter smith snow song soul spell spirit stone stoney
        strength strike striker strong sword timber tough true winter wise wolf worker
        wrath wrought
      </Words>
      <Reject>
        Blackface Brownface
      </Reject>
    </Join>
  </Join>
</NameGen>
